import { Component } from '@angular/core';
import { NavController, NavParams, App } from 'ionic-angular';
import { Http , Headers ,RequestOptions } from '@angular/http';
import { HttpService } from '../../../providers/http-service/http-service';
import {Color} from "highcharts";
import {SubNodeDetailPage} from "../subnode_detail/subnode_detail"

/**
 * Generated class for the DevicePage page.
 *
 * See http://ionicframework.com/docs/components/#navigation for more info
 * on Ionic pages and navigation.
 */
@Component({
  selector: 'page-subnode',
  templateUrl: 'subnode.html',
})
export class SubNodePage {
    name:string;
    subnodeMsg = [{
        "subnodeId":"1",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"2",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"0",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"1",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"1",
        "subnode_valve_4":"1",
    },{
        "subnodeId":"2",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"3",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"4",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"5",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"6",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"7",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"8",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"9",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"10",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    },{
        "subnodeId":"11",
        "installpoint":"XXX",
        "subnode_alarmnum":"23",
        "subnode_noconfirmalarm":"12",
        "subnode_malnum":"1",
        "subnode_noconfirmmal":"1",
        "subnode_detectornum":"4",
        "subnode_valvenum":"4",
        "subnode_detector_1":"1",
        "subnode_detector_2":"1",
        "subnode_detector_3":"1",
        "subnode_detector_4":"0",
        "subnode_valve_1":"1",
        "subnode_valve_2":"1",
        "subnode_valve_3":"0",
        "subnode_valve_4":"0",
    }];

    constructor(public http:Http,
                public app:App,
                public navCtrl: NavController,
                public navParams: NavParams,
                private httpService: HttpService,

    ) {
        this.name = this.navParams.data;
    }
    setup(){
        
    }
    getdetailMsg(item){
        this.app.getRootNav().push(SubNodeDetailPage,item);
    }
}
